# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ONQ7SoT-KmWDfMNx-c1Q75m_pOa0kWuj
"""

# =============================================================
#   IMDB Movie Review Classifier by Sithole
#   FINAL Streamlit Web App (Cloud-Ready)
# =============================================================

import streamlit as st
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences
import re

# -------------------------------------------------------------
# Streamlit Page Settings
# -------------------------------------------------------------
st.set_page_config(
    page_title="IMDB Movie Review Classifier by Sithole",
    page_icon="🎬",
    layout="wide"
)

# -------------------------------------------------------------
# Load IMDB Word Index
# -------------------------------------------------------------
word_index = tf.keras.datasets.imdb.get_word_index()

reverse_index = {value + 3: key for key, value in word_index.items()}
reverse_index[0] = "<PAD>"
reverse_index[1] = "<START>"
reverse_index[2] = "<UNK>"
reverse_index[3] = "<UNUSED>"


# -------------------------------------------------------------
# Load the Trained RNN Model
# -------------------------------------------------------------
@st.cache_resource
def load_model():
    """Load your trained RNN model"""
    try:
        model = tf.keras.models.load_model('my_movie_review_rnn.h5')
        # compile to avoid metric warning
        model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
        return model
    except:
        st.error("Model file NOT found. Upload 'my_movie_review_rnn.h5'.")
        return None

model = load_model()


# -------------------------------------------------------------
# Text Preprocessing
# -------------------------------------------------------------
def preprocess_text(text):
    text = re.sub(r"[^a-zA-Z\s]", "", text.lower())
    words = text.split()
    seq = []

    for word in words:
        idx = word_index.get(word, None)
        if idx is not None and idx < 10000:
            seq.append(idx + 3)

    return seq


def predict_sentiment(model, text):
    seq = preprocess_text(text)
    if len(seq) == 0:
        return "Neutral", 0.5, 0.5

    padded = pad_sequences([seq], maxlen=500, padding='post')
    raw_score = float(model.predict(padded, verbose=0)[0][0])

    sentiment = "Positive" if raw_score >= 0.5 else "Negative"
    confidence = raw_score if raw_score >= 0.5 else 1 - raw_score
    return sentiment, confidence, raw_score


# -------------------------------------------------------------
# Web Interface
# -------------------------------------------------------------
st.title("🎬 IMDB Movie Review Classifier by Sithole")
st.markdown("---")

if model is None:
    st.stop()


# -------------------------------------------------------------
# Automatic Predictions for 5 Sample Reviews
# -------------------------------------------------------------
st.header("📝 Five Sample Movie Reviews (Auto Classified)")

sample_reviews = [
    "This movie was absolutely fantastic! The acting was superb and the storyline kept me engaged throughout.",
    "Terrible movie. Poor acting, boring plot, and awful direction. Would not recommend to anyone.",
    "A decent film with some good moments, but overall it felt average and forgettable.",
    "Brilliant cinematography and outstanding performances make this a must-watch masterpiece.",
    "I fell asleep halfway through. The movie was slow-paced and lacked any exciting elements."
]

for i, review in enumerate(sample_reviews, 1):

    sentiment, confidence, raw = predict_sentiment(model, review)

    with st.expander(f"Review {i}: {sentiment} ({confidence:.1%})"):
        st.write(f"**Review:** {review}")

        col1, col2, col3 = st.columns(3)
        col1.metric("Sentiment", sentiment)
        col2.metric("Confidence", f"{confidence:.2%}")
        col3.metric("Raw Score", f"{raw:.4f}")

        if sentiment == "Positive":
            st.success("✔ Positive Review")
        else:
            st.error("✘ Negative Review")


st.markdown("---")


# -------------------------------------------------------------
# User Input Review
# -------------------------------------------------------------
st.header("🔍 Try Your Own Review")
user_review = st.text_area("Type your movie review below:", height=150)

if st.button("Analyze Review"):
    if user_review.strip():
        sentiment, confidence, raw = predict_sentiment(model, user_review)

        st.subheader("Result:")
        col1, col2, col3 = st.columns(3)
        col1.metric("Sentiment", sentiment)
        col2.metric("Confidence", f"{confidence:.2%}")
        col3.metric("Raw Score", f"{raw:.4f}")

        if sentiment == "Positive":
            st.balloons()
        elif sentiment == "Negative":
            st.warning("⚠ Negative Review Detected")
    else:
        st.warning("Please enter a review first.")